/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scientificccalculator;

/**
 *
 * @author calle
 */
public class MainFrame extends javax.swing.JFrame {
    
    ScientificCalculator basic = new ScientificCalculator();
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        txtEntrada.setText("0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtEntrada = new javax.swing.JTextField();
        btnNumUno = new javax.swing.JButton();
        btnNumDos = new javax.swing.JButton();
        btnNumTres = new javax.swing.JButton();
        btnNumCuatro = new javax.swing.JButton();
        btnNumCinco = new javax.swing.JButton();
        btnNumSeis = new javax.swing.JButton();
        btnNumSiete = new javax.swing.JButton();
        btnNumOcho = new javax.swing.JButton();
        btnNumNueve = new javax.swing.JButton();
        btnOpDividir = new javax.swing.JButton();
        btnOpMultiplicar = new javax.swing.JButton();
        btnOpSumar = new javax.swing.JButton();
        btnOpRestar = new javax.swing.JButton();
        btnNumCero = new javax.swing.JButton();
        btnIgual = new javax.swing.JButton();
        btnPunto = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        btnCE = new javax.swing.JButton();
        registroHistorial = new javax.swing.JTextField();
        funciones = new javax.swing.JPanel();
        btnFnRaiz = new javax.swing.JButton();
        btnFnPowTwo = new javax.swing.JButton();
        btnFnPowN = new javax.swing.JButton();
        btnFnSin = new javax.swing.JButton();
        btnFnCos = new javax.swing.JButton();
        btnFnTan = new javax.swing.JButton();
        btnFnModulo = new javax.swing.JButton();
        btnFnEuler = new javax.swing.JButton();
        btnFnLog = new javax.swing.JButton();
        btnFnNotation = new javax.swing.JButton();
        javax.swing.JButton btnNumPI = new javax.swing.JButton();
        btnFnFactorial = new javax.swing.JButton();
        btnFnMoreLess = new javax.swing.JButton();
        btnGrupR = new javax.swing.JButton();
        btnGrupL = new javax.swing.JButton();
        btnFnDx = new javax.swing.JButton();
        btnFnFx = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtEntrada.setBackground(new java.awt.Color(238, 238, 238));
        txtEntrada.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        txtEntrada.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtEntrada.setBorder(null);
        txtEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEntradaActionPerformed(evt);
            }
        });

        btnNumUno.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnNumUno.setText("1");
        btnNumUno.setToolTipText("");
        btnNumUno.setBorderPainted(false);
        btnNumUno.setContentAreaFilled(false);
        btnNumUno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNumUno.setFocusable(false);
        btnNumUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumUnoActionPerformed(evt);
            }
        });

        btnNumDos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnNumDos.setText("2");
        btnNumDos.setToolTipText("");
        btnNumDos.setBorderPainted(false);
        btnNumDos.setContentAreaFilled(false);
        btnNumDos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNumDos.setFocusable(false);
        btnNumDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumDosActionPerformed(evt);
            }
        });

        btnNumTres.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnNumTres.setText("3");
        btnNumTres.setToolTipText("");
        btnNumTres.setBorderPainted(false);
        btnNumTres.setContentAreaFilled(false);
        btnNumTres.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNumTres.setFocusable(false);
        btnNumTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumTresActionPerformed(evt);
            }
        });

        btnNumCuatro.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnNumCuatro.setText("4");
        btnNumCuatro.setToolTipText("");
        btnNumCuatro.setBorderPainted(false);
        btnNumCuatro.setContentAreaFilled(false);
        btnNumCuatro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNumCuatro.setFocusable(false);
        btnNumCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumCuatroActionPerformed(evt);
            }
        });

        btnNumCinco.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnNumCinco.setText("5");
        btnNumCinco.setToolTipText("");
        btnNumCinco.setBorderPainted(false);
        btnNumCinco.setContentAreaFilled(false);
        btnNumCinco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNumCinco.setFocusable(false);
        btnNumCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumCincoActionPerformed(evt);
            }
        });

        btnNumSeis.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnNumSeis.setText("6");
        btnNumSeis.setToolTipText("");
        btnNumSeis.setBorderPainted(false);
        btnNumSeis.setContentAreaFilled(false);
        btnNumSeis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNumSeis.setFocusable(false);
        btnNumSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumSeisActionPerformed(evt);
            }
        });

        btnNumSiete.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnNumSiete.setText("7");
        btnNumSiete.setToolTipText("");
        btnNumSiete.setBorderPainted(false);
        btnNumSiete.setContentAreaFilled(false);
        btnNumSiete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNumSiete.setFocusable(false);
        btnNumSiete.setPreferredSize(new java.awt.Dimension(61, 29));
        btnNumSiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumSieteActionPerformed(evt);
            }
        });

        btnNumOcho.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnNumOcho.setText("8");
        btnNumOcho.setToolTipText("");
        btnNumOcho.setBorderPainted(false);
        btnNumOcho.setContentAreaFilled(false);
        btnNumOcho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNumOcho.setFocusable(false);
        btnNumOcho.setPreferredSize(new java.awt.Dimension(61, 29));
        btnNumOcho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumOchoActionPerformed(evt);
            }
        });

        btnNumNueve.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnNumNueve.setText("9");
        btnNumNueve.setToolTipText("");
        btnNumNueve.setBorderPainted(false);
        btnNumNueve.setContentAreaFilled(false);
        btnNumNueve.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNumNueve.setFocusable(false);
        btnNumNueve.setPreferredSize(new java.awt.Dimension(61, 29));
        btnNumNueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumNueveActionPerformed(evt);
            }
        });

        btnOpDividir.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        btnOpDividir.setText("/");
        btnOpDividir.setToolTipText("");
        btnOpDividir.setBorderPainted(false);
        btnOpDividir.setContentAreaFilled(false);
        btnOpDividir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOpDividir.setFocusable(false);
        btnOpDividir.setMaximumSize(new java.awt.Dimension(61, 29));
        btnOpDividir.setPreferredSize(new java.awt.Dimension(61, 29));
        btnOpDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpDividirActionPerformed(evt);
            }
        });

        btnOpMultiplicar.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        btnOpMultiplicar.setText("*");
        btnOpMultiplicar.setToolTipText("");
        btnOpMultiplicar.setBorderPainted(false);
        btnOpMultiplicar.setContentAreaFilled(false);
        btnOpMultiplicar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOpMultiplicar.setFocusable(false);
        btnOpMultiplicar.setPreferredSize(new java.awt.Dimension(61, 29));
        btnOpMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpMultiplicarActionPerformed(evt);
            }
        });

        btnOpSumar.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        btnOpSumar.setText("+");
        btnOpSumar.setToolTipText("");
        btnOpSumar.setBorderPainted(false);
        btnOpSumar.setContentAreaFilled(false);
        btnOpSumar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOpSumar.setFocusable(false);
        btnOpSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpSumarActionPerformed(evt);
            }
        });

        btnOpRestar.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        btnOpRestar.setText("-");
        btnOpRestar.setToolTipText("");
        btnOpRestar.setBorderPainted(false);
        btnOpRestar.setContentAreaFilled(false);
        btnOpRestar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOpRestar.setFocusable(false);
        btnOpRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpRestarActionPerformed(evt);
            }
        });

        btnNumCero.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnNumCero.setText("0");
        btnNumCero.setToolTipText("");
        btnNumCero.setBorderPainted(false);
        btnNumCero.setContentAreaFilled(false);
        btnNumCero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNumCero.setFocusable(false);
        btnNumCero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumCeroActionPerformed(evt);
            }
        });

        btnIgual.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        btnIgual.setText("=");
        btnIgual.setToolTipText("");
        btnIgual.setBorderPainted(false);
        btnIgual.setContentAreaFilled(false);
        btnIgual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIgual.setFocusable(false);
        btnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIgualActionPerformed(evt);
            }
        });

        btnPunto.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnPunto.setText(".");
        btnPunto.setToolTipText("");
        btnPunto.setBorderPainted(false);
        btnPunto.setContentAreaFilled(false);
        btnPunto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPunto.setFocusable(false);
        btnPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntoActionPerformed(evt);
            }
        });

        btnC.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        btnC.setText("C");
        btnC.setToolTipText("");
        btnC.setBorderPainted(false);
        btnC.setContentAreaFilled(false);
        btnC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnC.setFocusPainted(false);
        btnC.setFocusable(false);
        btnC.setPreferredSize(new java.awt.Dimension(61, 29));
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });

        btnCE.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        btnCE.setText("CE");
        btnCE.setToolTipText("");
        btnCE.setBorderPainted(false);
        btnCE.setContentAreaFilled(false);
        btnCE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCE.setFocusPainted(false);
        btnCE.setFocusable(false);
        btnCE.setPreferredSize(new java.awt.Dimension(61, 29));
        btnCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCEActionPerformed(evt);
            }
        });

        registroHistorial.setEditable(false);
        registroHistorial.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        registroHistorial.setForeground(new java.awt.Color(153, 153, 153));
        registroHistorial.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        registroHistorial.setBorder(null);
        registroHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroHistorialActionPerformed(evt);
            }
        });

        funciones.setBackground(new java.awt.Color(229, 229, 229));
        funciones.setFocusable(false);

        btnFnRaiz.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        btnFnRaiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/scientificccalculator/sqrt.png"))); // NOI18N
        btnFnRaiz.setToolTipText("");
        btnFnRaiz.setBorderPainted(false);
        btnFnRaiz.setContentAreaFilled(false);
        btnFnRaiz.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFnRaiz.setFocusable(false);
        btnFnRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFnRaizActionPerformed(evt);
            }
        });

        btnFnPowTwo.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        btnFnPowTwo.setText("x²");
        btnFnPowTwo.setToolTipText("");
        btnFnPowTwo.setBorderPainted(false);
        btnFnPowTwo.setContentAreaFilled(false);
        btnFnPowTwo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFnPowTwo.setFocusable(false);
        btnFnPowTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFnPowTwoActionPerformed(evt);
            }
        });

        btnFnPowN.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        btnFnPowN.setText("x^");
        btnFnPowN.setToolTipText("");
        btnFnPowN.setBorderPainted(false);
        btnFnPowN.setContentAreaFilled(false);
        btnFnPowN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFnPowN.setFocusable(false);
        btnFnPowN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFnPowNActionPerformed(evt);
            }
        });

        btnFnSin.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnFnSin.setText("Sin");
        btnFnSin.setToolTipText("");
        btnFnSin.setBorderPainted(false);
        btnFnSin.setContentAreaFilled(false);
        btnFnSin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFnSin.setFocusable(false);
        btnFnSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFnSinActionPerformed(evt);
            }
        });

        btnFnCos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnFnCos.setText("Cos");
        btnFnCos.setToolTipText("");
        btnFnCos.setBorderPainted(false);
        btnFnCos.setContentAreaFilled(false);
        btnFnCos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFnCos.setFocusable(false);
        btnFnCos.setRequestFocusEnabled(false);
        btnFnCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFnCosActionPerformed(evt);
            }
        });

        btnFnTan.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnFnTan.setText("Tan");
        btnFnTan.setToolTipText("");
        btnFnTan.setBorderPainted(false);
        btnFnTan.setContentAreaFilled(false);
        btnFnTan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFnTan.setFocusable(false);
        btnFnTan.setMargin(null);
        btnFnTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFnTanActionPerformed(evt);
            }
        });

        btnFnModulo.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        btnFnModulo.setText("Mod");
        btnFnModulo.setToolTipText("");
        btnFnModulo.setBorderPainted(false);
        btnFnModulo.setContentAreaFilled(false);
        btnFnModulo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFnModulo.setFocusable(false);
        btnFnModulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFnModuloActionPerformed(evt);
            }
        });

        btnFnEuler.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnFnEuler.setText("Exp");
        btnFnEuler.setToolTipText("");
        btnFnEuler.setBorderPainted(false);
        btnFnEuler.setContentAreaFilled(false);
        btnFnEuler.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFnEuler.setFocusable(false);
        btnFnEuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFnEulerActionPerformed(evt);
            }
        });

        btnFnLog.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnFnLog.setText("Log");
        btnFnLog.setToolTipText("");
        btnFnLog.setBorderPainted(false);
        btnFnLog.setContentAreaFilled(false);
        btnFnLog.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFnLog.setFocusable(false);
        btnFnLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFnLogActionPerformed(evt);
            }
        });

        btnFnNotation.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnFnNotation.setText("10^");
        btnFnNotation.setToolTipText("");
        btnFnNotation.setBorderPainted(false);
        btnFnNotation.setContentAreaFilled(false);
        btnFnNotation.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFnNotation.setFocusable(false);
        btnFnNotation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFnNotationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout funcionesLayout = new javax.swing.GroupLayout(funciones);
        funciones.setLayout(funcionesLayout);
        funcionesLayout.setHorizontalGroup(
            funcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(funcionesLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(funcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnFnRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnFnPowTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(funcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFnPowN, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFnNotation, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(funcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFnSin, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFnLog, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(funcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(funcionesLayout.createSequentialGroup()
                        .addComponent(btnFnCos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFnTan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(funcionesLayout.createSequentialGroup()
                        .addComponent(btnFnEuler, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFnModulo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        funcionesLayout.setVerticalGroup(
            funcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(funcionesLayout.createSequentialGroup()
                .addGroup(funcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFnPowTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFnCos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFnTan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(funcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(funcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnFnModulo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnFnEuler, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnFnRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(funcionesLayout.createSequentialGroup()
                .addComponent(btnFnSin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFnLog, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(funcionesLayout.createSequentialGroup()
                .addComponent(btnFnPowN, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFnNotation, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnNumPI.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        btnNumPI.setText("π");
        btnNumPI.setToolTipText("");
        btnNumPI.setBorderPainted(false);
        btnNumPI.setContentAreaFilled(false);
        btnNumPI.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNumPI.setFocusable(false);
        btnNumPI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumPIActionPerformed(evt);
            }
        });

        btnFnFactorial.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        btnFnFactorial.setText("n!");
        btnFnFactorial.setToolTipText("");
        btnFnFactorial.setBorderPainted(false);
        btnFnFactorial.setContentAreaFilled(false);
        btnFnFactorial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFnFactorial.setFocusable(false);
        btnFnFactorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFnFactorialActionPerformed(evt);
            }
        });

        btnFnMoreLess.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        btnFnMoreLess.setText("±");
        btnFnMoreLess.setToolTipText("");
        btnFnMoreLess.setBorderPainted(false);
        btnFnMoreLess.setContentAreaFilled(false);
        btnFnMoreLess.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFnMoreLess.setFocusable(false);
        btnFnMoreLess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFnMoreLessActionPerformed(evt);
            }
        });

        btnGrupR.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        btnGrupR.setText(")");
        btnGrupR.setToolTipText("");
        btnGrupR.setBorderPainted(false);
        btnGrupR.setContentAreaFilled(false);
        btnGrupR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGrupR.setFocusable(false);
        btnGrupR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrupRActionPerformed(evt);
            }
        });

        btnGrupL.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        btnGrupL.setText("(");
        btnGrupL.setToolTipText("");
        btnGrupL.setBorderPainted(false);
        btnGrupL.setContentAreaFilled(false);
        btnGrupL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGrupL.setFocusable(false);
        btnGrupL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrupLActionPerformed(evt);
            }
        });

        btnFnDx.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        btnFnDx.setText("dx");
        btnFnDx.setToolTipText("");
        btnFnDx.setBorderPainted(false);
        btnFnDx.setContentAreaFilled(false);
        btnFnDx.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFnDx.setFocusable(false);
        btnFnDx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFnDxActionPerformed(evt);
            }
        });

        btnFnFx.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        btnFnFx.setText("f(x)");
        btnFnFx.setToolTipText("");
        btnFnFx.setBorderPainted(false);
        btnFnFx.setContentAreaFilled(false);
        btnFnFx.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFnFx.setFocusable(false);
        btnFnFx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFnFxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(funciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnFnFactorial, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addComponent(btnNumCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnFnMoreLess, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnNumUno, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnGrupL, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnGrupR, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnNumCero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnNumDos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPunto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNumTres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnOpSumar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNumSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnOpRestar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNumPI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFnFx, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNumCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnFnDx, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnCE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnNumSiete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnNumOcho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnNumNueve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnOpDividir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnOpMultiplicar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registroHistorial, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtEntrada))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(registroHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(funciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOpDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCE, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFnDx, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFnFx, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNumNueve, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOpMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNumOcho, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNumSiete, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNumPI, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNumCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNumCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNumSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOpRestar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFnFactorial, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNumDos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNumUno, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNumTres, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOpSumar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFnMoreLess, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNumCero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrupR, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrupL, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNumOchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumOchoActionPerformed
        //Envia la equivalencia numerica de la tecla presionada
        basic.NumPresionado(8);
        //Establece los digitos de @txtEntrada actualizandolos cada vez que se ingresa un numero
        txtEntrada.setText(basic.getData());
    }//GEN-LAST:event_btnNumOchoActionPerformed

    private void btnNumCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumCincoActionPerformed
        basic.NumPresionado(5);
        txtEntrada.setText(basic.getData());
    }//GEN-LAST:event_btnNumCincoActionPerformed

    private void btnNumDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumDosActionPerformed
        basic.NumPresionado(2);
        txtEntrada.setText(basic.getData());
    }//GEN-LAST:event_btnNumDosActionPerformed

    private void btnNumNueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumNueveActionPerformed
        basic.NumPresionado(9);
        txtEntrada.setText(basic.getData());
    }//GEN-LAST:event_btnNumNueveActionPerformed

    private void btnNumUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumUnoActionPerformed
        basic.NumPresionado(1);
        txtEntrada.setText(basic.getData());
    }//GEN-LAST:event_btnNumUnoActionPerformed

    private void btnOpDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpDividirActionPerformed
        basic.opPresionada("/", txtEntrada.getText());
        txtEntrada.setText("0");
    }//GEN-LAST:event_btnOpDividirActionPerformed

    private void btnOpMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpMultiplicarActionPerformed
        basic.opPresionada("*", txtEntrada.getText());
        txtEntrada.setText("0");
    }//GEN-LAST:event_btnOpMultiplicarActionPerformed

    private void btnOpSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpSumarActionPerformed
        basic.opPresionada("+", txtEntrada.getText());
        txtEntrada.setText("0");
    }//GEN-LAST:event_btnOpSumarActionPerformed

    private void btnOpRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpRestarActionPerformed
        basic.opPresionada("-", txtEntrada.getText());
        txtEntrada.setText("0");
    }//GEN-LAST:event_btnOpRestarActionPerformed

    private void btnNumCeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumCeroActionPerformed
        basic.NumPresionado("0");
        txtEntrada.setText(basic.getData());
    }//GEN-LAST:event_btnNumCeroActionPerformed

    private void btnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIgualActionPerformed
        /*
            Como ya se conoce el valor de la primer entrada y la operacion a realizar,
            se procede con el calculo del total
        */
        String calculo = String.valueOf(basic.total(txtEntrada.getText()));
        txtEntrada.setText(calculo);
    }//GEN-LAST:event_btnIgualActionPerformed

    private void btnPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuntoActionPerformed
        basic.NumPresionado(".");
        txtEntrada.setText(basic.getData());
    }//GEN-LAST:event_btnPuntoActionPerformed

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        basic.C(txtEntrada.getText());
        txtEntrada.setText("0");
    }//GEN-LAST:event_btnCActionPerformed

    private void btnCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCEActionPerformed
        basic.opPresionada("CE", txtEntrada.getText());
        txtEntrada.setText("0");
    }//GEN-LAST:event_btnCEActionPerformed

    private void btnNumSieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumSieteActionPerformed
        basic.NumPresionado(7);
        txtEntrada.setText(basic.getData());
    }//GEN-LAST:event_btnNumSieteActionPerformed

    private void btnNumCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumCuatroActionPerformed
        basic.NumPresionado(4);
        txtEntrada.setText(basic.getData());
    }//GEN-LAST:event_btnNumCuatroActionPerformed

    private void btnNumSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumSeisActionPerformed
        basic.NumPresionado(6);
        txtEntrada.setText(basic.getData());
    }//GEN-LAST:event_btnNumSeisActionPerformed

    private void btnNumTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumTresActionPerformed
        basic.NumPresionado(3);
        txtEntrada.setText(basic.getData());
    }//GEN-LAST:event_btnNumTresActionPerformed

    private void txtEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEntradaActionPerformed
        
    }//GEN-LAST:event_txtEntradaActionPerformed

    private void btnFnNotationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFnNotationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFnNotationActionPerformed

    private void btnFnLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFnLogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFnLogActionPerformed

    private void btnFnEulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFnEulerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFnEulerActionPerformed

    private void btnFnModuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFnModuloActionPerformed
        basic.opPresionada("%", txtEntrada.getText());
        txtEntrada.setText("0");
    }//GEN-LAST:event_btnFnModuloActionPerformed

    private void btnFnTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFnTanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFnTanActionPerformed

    private void btnFnCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFnCosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFnCosActionPerformed

    private void btnFnSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFnSinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFnSinActionPerformed

    private void btnFnPowNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFnPowNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFnPowNActionPerformed

    private void btnFnPowTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFnPowTwoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFnPowTwoActionPerformed

    private void btnFnRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFnRaizActionPerformed
        basic.opPresionada("v/", txtEntrada.getText());
        txtEntrada.setText("0");
    }//GEN-LAST:event_btnFnRaizActionPerformed

    private void btnNumPIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumPIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNumPIActionPerformed

    private void btnFnFactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFnFactorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFnFactorialActionPerformed

    private void btnFnMoreLessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFnMoreLessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFnMoreLessActionPerformed

    private void btnGrupRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrupRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGrupRActionPerformed

    private void btnGrupLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrupLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGrupLActionPerformed

    private void btnFnDxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFnDxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFnDxActionPerformed

    private void btnFnFxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFnFxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFnFxActionPerformed

    private void registroHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroHistorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registroHistorialActionPerformed
    
    public static void main(String[] args) {
        
        MainFrame basica = new MainFrame();
        
        basica.setVisible(true);
        basica.setTitle("Calculadora Científica");
        basica.setLocationRelativeTo(null);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnCE;
    private javax.swing.JButton btnFnCos;
    private javax.swing.JButton btnFnDx;
    private javax.swing.JButton btnFnEuler;
    private javax.swing.JButton btnFnFactorial;
    private javax.swing.JButton btnFnFx;
    private javax.swing.JButton btnFnLog;
    private javax.swing.JButton btnFnModulo;
    private javax.swing.JButton btnFnMoreLess;
    private javax.swing.JButton btnFnNotation;
    private javax.swing.JButton btnFnPowN;
    private javax.swing.JButton btnFnPowTwo;
    private javax.swing.JButton btnFnRaiz;
    private javax.swing.JButton btnFnSin;
    private javax.swing.JButton btnFnTan;
    private javax.swing.JButton btnGrupL;
    private javax.swing.JButton btnGrupR;
    private javax.swing.JButton btnIgual;
    private javax.swing.JButton btnNumCero;
    private javax.swing.JButton btnNumCinco;
    private javax.swing.JButton btnNumCuatro;
    private javax.swing.JButton btnNumDos;
    private javax.swing.JButton btnNumNueve;
    private javax.swing.JButton btnNumOcho;
    private javax.swing.JButton btnNumSeis;
    private javax.swing.JButton btnNumSiete;
    private javax.swing.JButton btnNumTres;
    private javax.swing.JButton btnNumUno;
    private javax.swing.JButton btnOpDividir;
    private javax.swing.JButton btnOpMultiplicar;
    private javax.swing.JButton btnOpRestar;
    private javax.swing.JButton btnOpSumar;
    private javax.swing.JButton btnPunto;
    private javax.swing.JPanel funciones;
    private javax.swing.JTextField registroHistorial;
    private javax.swing.JTextField txtEntrada;
    // End of variables declaration//GEN-END:variables
}
